# Generated by Django 4.1.3 on 2023-04-12 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distqueue', '0005_rename_subscription_consumer_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='partitionReplicaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_port', models.PositiveIntegerField()),
                ('peer1', models.PositiveIntegerField()),
                ('peer2', models.PositiveIntegerField()),
                ('topic_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_name_prd', to='distqueue.topic')),
            ],
        ),
    ]
